module.exports = [
  {name: 'TestCheckElementFully_Fluent', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckElementFully_Fluent', executionMode: {isCssStitching: true}},
  {name: 'TestCheckElementFully_Fluent', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckFrame', executionMode: {isVisualGrid: true}, disabled: true},
  {name: 'TestCheckFrame', executionMode: {isCssStitching: true}, disabled: true},
  {name: 'TestCheckFrame', executionMode: {isScrollStitching: true}, disabled: true},
  {name: 'TestCheckFrame_Fluent', executionMode: {isVisualGrid: true}, disabled: true},
  {name: 'TestCheckFrame_Fluent', executionMode: {isCssStitching: true}, disabled: true},
  {name: 'TestCheckFrame_Fluent', executionMode: {isScrollStitching: true}, disabled: true},
  {name: 'TestCheckElementFully_Fluent', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckElementFully_Fluent', executionMode: {isCssStitching: true}},
  {name: 'TestCheckElementFully_Fluent', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckWindow', executionMode: {isVisualGrid: true}, disabled: true},
  {name: 'TestCheckWindow', executionMode: {isCssStitching: true}},
  {name: 'TestCheckWindow', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckWindowViewport', executionMode: {isVisualGrid: true}, disabled: true},
  {name: 'TestCheckWindowViewport', executionMode: {isCssStitching: true}},
  {name: 'TestCheckWindowViewport', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckWindow_Fluent', executionMode: {isVisualGrid: true}, disabled: true},
  {name: 'TestCheckWindow_Fluent', executionMode: {isCssStitching: true}},
  {name: 'TestCheckWindow_Fluent', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckRegion', executionMode: {isCssStitching: true}},
  {name: 'TestCheckRegion', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckRegion', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckRegion2', executionMode: {isCssStitching: true}},
  {name: 'TestCheckRegion2', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckRegion2', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckRegionByCoordinates_Fluent', executionMode: {isCssStitching: true}},
  {name: 'TestCheckRegionByCoordinates_Fluent', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckRegionByCoordinates_Fluent', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckRegionBySelectorAfterManualScroll_Fluent', executionMode: {isCssStitching: true}},
  {name: 'TestCheckRegionBySelectorAfterManualScroll_Fluent', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckRegionBySelectorAfterManualScroll_Fluent', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckFixedRegion', executionMode: {isCssStitching: true}},
  {name: 'TestCheckFixedRegion', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckFixedRegion', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckFixedRegion_Fully', executionMode: {isCssStitching: true}},
  {name: 'TestCheckFixedRegion_Fully', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckFixedRegion_Fully', executionMode: {isScrollStitching: true}},
  {name: 'TestSimpleModal', executionMode: {isCssStitching: true}},
  {name: 'TestSimpleModal', executionMode: {isVisualGrid: true}},
  {name: 'TestSimpleModal', executionMode: {isScrollStitching: true}},

  {name: 'TestCheckWindowWithIgnoreBySelector_Fluent', executionMode: {isCssStitching: true}},
  {name: 'TestCheckWindowWithIgnoreBySelector_Fluent', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckWindowWithIgnoreBySelector_Fluent', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckWindowWithIgnoreBySelector_Centered_Fluent', executionMode: {isCssStitching: true}},
  {name: 'TestCheckWindowWithIgnoreBySelector_Centered_Fluent', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckWindowWithIgnoreBySelector_Centered_Fluent', executionMode: {isScrollStitching: true}},
  {name: 'TestCheckWindowWithIgnoreBySelector_Stretched_Fluent', executionMode: {isCssStitching: true}},
  {name: 'TestCheckWindowWithIgnoreBySelector_Stretched_Fluent', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckWindowWithIgnoreBySelector_Stretched_Fluent', executionMode: {isScrollStitching: true}},

  {name: 'TestDoubleCheckWindow', executionMode: {isCssStitching: true}},
  {name: 'TestDoubleCheckWindow', executionMode: {isVisualGrid: true}},
  {name: 'TestDoubleCheckWindow', executionMode: {isScrollStitching: true}},

  {name: 'TestCheckFixedRegion', executionMode: {isCssStitching: true}},
  {name: 'TestCheckFixedRegion', executionMode: {isVisualGrid: true}},
  {name: 'TestCheckFixedRegion', executionMode: {isScrollStitching: true}},
]
